version: "3.8"
services:
  web:
    build: .
    container_name: messaging_app
    ports:
      - "8000:8000"
    
  db:
    image: postgres
    container_name: messaging_db
    environment:
      POSTGRES_USER: ${MYSQL_USER}
      POSTGRES_PASSWORD: ${MYSQL_PASSWORD}
      POSTGRES_DB: ${MYSQL_DB}